FROM python:3.6 AS base
WORKDIR /app
COPY . /app

FROM base AS dependencies  
RUN pip install -r /app/requirements.txt

FROM dependencies AS build  
WORKDIR /app
COPY . /app

FROM python:3.6-alpine3.7 AS release  
# Create app directory
WORKDIR /app

COPY --from=dependencies /app/requirements.txt ./
COPY --from=dependencies /root/.cache /root/.cache

# Install app dependencies
RUN pip install -r requirements.txt
COPY --from=build /app/ ./
CMD ["python3", "-m", "flask", "run", "--host=0.0.0.0"]